name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'
    - name: Compile Pyinstaller Bootloader
      run: |
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller/bootloader
        python ./waf all
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd pyinstaller
        pip install .
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v4.0.0
      with:
        install-only: true
    - name: Build executable (Windows)
      run: |
        pyinstaller --onefile --windowed --add-data "resources:resources" --name youareanidiot_${{ github.ref_name }} idiot.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: youareanidiot-Windows
        path: dist/youareanidiot_${{ github.ref_name }}.exe

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/youareanidiot_${{ github.ref_name }}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
